spring:
  application:
    name: mobile-api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
             - http://localhost:5173
            allowedHeaders: '*'
            allowedMethods:
              - GET
              - POST
              - PATCH
              - DELETE
      httpclient:
        response-timeout: 3s
server:
  port: 8080
jwt:
  secret: Y8G8AX58H0Z3YIHEHP9VT5RY58H79Q20